name: Build Windows EXE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: |
          pip install poetry
          poetry config virtualenvs.create false

      - name: Install dependencies
        run: poetry install --with build

      - name: Build with PyInstaller
        run: |
          poetry run pyinstaller --onefile --name "payroll-worksheets" src/app/main.py --hidden-import=holidays.countries

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: payroll-worksheets
          path: dist/payroll-worksheets.exe
